# Generated by Django 2.2.4 on 2019-08-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='firebase_app',
            field=models.CharField(default='[DEFAULT]', max_length=25),
            preserve_default=False,
        ),
    ]
