# Generated by Django 2.2.10 on 2020-02-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcm', '0002_device_firebase_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='firebase_app',
            field=models.CharField(default='[DEFAULT]', max_length=25),
        ),
    ]
